In [1]:
import numpy as np

In [3]:
a = np.array([[10,15]])
b = np.array([[20,9]])
print(a)
print(b)
print()

a+b

[[10 15]]
[[20  9]]



array([[30, 24]])

In [4]:
a.T + b.T

array([[30],
       [24]])

In [5]:
a-b

array([[-10,   6]])

In [6]:
(a-b).T

array([[-10],
       [  6]])

In [7]:
# scaler 
a = 2
u = np.array([[30,15]])
(a*u).T

array([[60],
       [30]])

In [9]:
# Dot product of 2 vectors
# for 2-d vectors, it is equivalent to matrix multiplication
 
u = np.array([10,20])
v = np.array([25,6])
print(10*25 + 20*6)
np.dot(u,v)

370


370